version: "3.4"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5050:5050
    command: npm run dev
